### ISSUE TITLE
Test failures caused by invalid database connection result in fatal error

### ISSUE THREAD

**Issue by Majkl578** [doctrine/dbal#3049]
When PHPUnit is started with invalid DB config in local phpunit.xml, it crashes with uncaught PHP fatal error.

```
$ vendor/bin/phpunit
PHPUnit 7.0.2 by Sebastian Bergmann and contributors.

Testing 
......SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS....   61 / 5181 (  1%)
..SSS............SS..............S.......SS...S.....S.SSS....  122 / 5181 (  2%)
............SS..SSSSSS......SSS..............SS...EEE........  183 / 5181 (  3%)
.SS...S............S.S.....S.................................  244 / 5181 (  4%)
...............EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE  305 / 5181 (  5%)
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEESSSEEEE  366 / 5181 (  7%)
ESSSSSSSSSEEEEESSSSPHP Fatal error:  Uncaught TypeError: Return value of PHPUnit\Framework\TestCase::getTestResultObject() must be an instance of PHPUnit\Framework\TestResult, null returned in /www/doctrine/dbal/vendor/phpunit/phpunit/src/Framework/TestCase.php:918
Stack trace:
#0 /www/doctrine/dbal/vendor/symfony/phpunit-bridge/Legacy/SymfonyTestsListenerTrait.php(182): PHPUnit\Framework\TestCase->getTestResultObject()
#1 /www/doctrine/dbal/vendor/symfony/phpunit-bridge/Legacy/SymfonyTestsListenerForV7.php(55): Symfony\Bridge\PhpUnit\Legacy\SymfonyTestsListenerTrait->startTest(Object(PHPUnit\Framework\WarningTestCase))
#2 /www/doctrine/dbal/vendor/phpunit/phpunit/src/Framework/TestResult.php(394): Symfony\Bridge\PhpUnit\Legacy\SymfonyTestsListenerForV7->startTest(Object(PHPUnit\Framework\WarningTestCase))
#3 /www/doctrine/dbal/vendor/phpunit/phpunit/src/Framework/TestResult.php(647): PHPUnit\Framework\TestResult->startTest(Object(PHPUnit\Framework\WarningTestCase))
#4 /www/doctrine/dbal/vendor/phpunit/phpunit/src/Framework/TestCase.php(679): PH in /www/doctrine/dbal/vendor/phpunit/phpunit/src/Framework/TestCase.php on line 918
```

**Comment by Majkl578** [comment]
Haven't seen this since then, it's possible it's been fixed upstream.

**Comment by morozov** [comment]
Still reproducible. Just caught it by trying to run PostgreSQL tests without installed extension:
```
↪ git rev-parse HEAD
f2d1f378645d63798c30cfadc9850650cc9536f3

↪ phpunit -c pdo-pgsql.phpunit.xml 
PHPUnit 7.0.3 by Sebastian Bergmann and contributors.

Testing 
......................SSSSS.....................................SSS..........   77 / 5254 (  1%)
..SS..............S.......SS...S.....S.SSS..........EE....SS..............SSS  154 / 5254 (  2%)
..............SS...SSS.........SS...S............S.S........SSS..SSS.........  231 / 5254 (  4%)
.............................EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE  308 / 5254 (  5%)
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEESSSEEEEEEEEEEEEEEEEEEEEES  385 / 5254 (  7%)
S
Fatal error: Uncaught TypeError: Return value of PHPUnit\Framework\TestCase::getTestResultObject() must be an instance of PHPUnit\Framework\TestResult, null returned in vendor/phpunit/phpunit/src/Framework/TestCase.php on line 918

TypeError: Return value of PHPUnit\Framework\TestCase::getTestResultObject() must be an instance of PHPUnit\Framework\TestResult, null returned in vendor/phpunit/phpunit/src/Framework/TestCase.php on line 918

Call Stack:
    0.0001     402832   1. {main}() vendor/phpunit/phpunit/phpunit:0
    0.0143     912104   2. PHPUnit\TextUI\Command::main() vendor/phpunit/phpunit/phpunit:53
    0.0143     912216   3. PHPUnit\TextUI\Command->run() vendor/phpunit/phpunit/src/TextUI/Command.php:153
    1.1181   33272280   4. PHPUnit\TextUI\TestRunner->doRun() vendor/phpunit/phpunit/src/TextUI/Command.php:205
    1.2080   33587864   5. PHPUnit\Framework\TestSuite->run() vendor/phpunit/phpunit/src/TextUI/TestRunner.php:508
    1.3688   33602952   6. PHPUnit\Framework\TestSuite->run() vendor/phpunit/phpunit/src/Framework/TestSuite.php:760
    2.1029   51942456   7. PHPUnit\Framework\TestSuite->run() vendor/phpunit/phpunit/src/Framework/TestSuite.php:760
    2.1055   51942984   8. PHPUnit\Framework\DataProviderTestSuite->run() vendor/phpunit/phpunit/src/Framework/TestSuite.php:760
    2.1057   51943648   9. PHPUnit\Framework\WarningTestCase->run() vendor/phpunit/phpunit/src/Framework/TestSuite.php:760
    2.1057   51943648  10. PHPUnit\Framework\TestResult->run() vendor/phpunit/phpunit/src/Framework/TestCase.php:679
    2.1057   51944024  11. PHPUnit\Framework\TestResult->startTest() vendor/phpunit/phpunit/src/Framework/TestResult.php:647
    2.1057   51944024  12. Symfony\Bridge\PhpUnit\Legacy\SymfonyTestsListenerForV7->startTest() vendor/phpunit/phpunit/src/Framework/TestResult.php:394
    2.1057   51944024  13. Symfony\Bridge\PhpUnit\Legacy\SymfonyTestsListenerTrait->startTest() vendor/symfony/phpunit-bridge/Legacy/SymfonyTestsListenerForV7.php:55
    2.1057   51944024  14. PHPUnit\Framework\WarningTestCase->getTestResultObject() vendor/symfony/phpunit-bridge/Legacy/SymfonyTestsListenerTrait.php:182
```

**Comment by Majkl578** [comment]
@morozov Could you try without Symfony listener installed/enabled? So we can report it on appropriate place. 👍 Thanks.

**Comment by morozov** [comment]
Doesn't fail this way without the listener!

**Comment by Majkl578** [comment]
Reported here: https://github.com/symfony/symfony/issues/26861
