### ISSUE TITLE
SQLSTATE[HY000] [2054] Server sent charset unknown to the client. Please, report to the developers

### ISSUE THREAD

**Issue by david1953** [doctrine/dbal#4371]
I am trying to install and use the latest version of PHPMaker 2021.  So far, it fails frequently with references to vendor source code.  So i don't know who i need to discuss this with.   I am using MySql version 8 and PHP version 7.4    The default for MySql charset defaulted to utf8mb4.  when that didn't work, i tried utf8, and that didn't work either.  

any message, hint or assistance would be greatly appreciated.  

this is the debug message I get: 

```
Slim Application Error
Type: Doctrine\DBAL\Exception\DriverException
Code: 0
Message: An exception occurred in driver: SQLSTATE[HY000] [2054] Server sent charset unknown to the client. Please, report to the developers
File: C:\Users\Public\website\pstest\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php
Line: 128
Trace: #0 C:\Users\Public\website\pstest\vendor\doctrine\dbal\lib\Doctrine\DBAL\DBALException.php(182): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDO\Exception))
#1 C:\Users\Public\website\pstest\vendor\doctrine\dbal\lib\Doctrine\DBAL\DBALException.php(169): Doctrine\DBAL\DBALException::wrapException(Object(Doctrine\DBAL\Driver\PDO\MySQL\Driver), Object(Doctrine\DBAL\Driver\PDO\Exception), 'An exception oc...')
#2 C:\Users\Public\website\pstest\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOMySql\Driver.php(30): Doctrine\DBAL\DBALException::driverException(Object(Doctrine\DBAL\Driver\PDO\MySQL\Driver), Object(Doctrine\DBAL\Driver\PDO\Exception))
#3 C:\Users\Public\website\pstest\vendor\doctrine\dbal\lib\Doctrine\DBAL\Connection.php(362): Doctrine\DBAL\Driver\PDOMySql\Driver->connect(Array, 'webaccess', 'Parsup-20', Array)
#4 C:\Users\Public\website\pstest\vendor\doctrine\dbal\lib\Doctrine\DBAL\Connection.php(1853): Doctrine\DBAL\Connection->connect()
#5 C:\Users\Public\website\pstest\vendor\doctrine\dbal\lib\Doctrine\DBAL\Connection.php(1241): Doctrine\DBAL\Connection->getWrappedConnection()
#6 C:\Users\Public\website\pstest\models\OrderDetails.php(500): Doctrine\DBAL\Connection->executeQuery('SELECT COUNT(*)...')
#7 C:\Users\Public\website\pstest\models\OrderDetails.php(600): PHPMaker2021\pstest\OrderDetails->getRecordCount('SELECT * FROM `...')
#8 C:\Users\Public\website\pstest\models\OrderDetailsList.php(939): PHPMaker2021\pstest\OrderDetails->listRecordCount()
```

**Comment by greg0ire** [comment]
I think you need to report this to the developers of the `pdo_mysql` driver.

**Comment by david1953** [comment]
Ok. I wasn’t sure so I thought I’d try you first.
Thanks.

Dave Dunbar
Phoenix, AZ
From my Surface Pro 3
