### ISSUE TITLE
When using prepared statements, exception is not thrown

### ISSUE THREAD

**Issue by mvorisek** [doctrine/dbal#5526]
### Bug Report

|    Q        |   A
|------------ | ------
| Version     | 3.3.7

#### Current behaviour

See repro code, when query is executed directly (/wo prepared statement), exception is thrown. But when using prepared statement, exception is not thrown.

This is inconsistent and dangerous. When query is executed on non-existent table, an exception must be always thrown.

#### How to reproduce

Run the following query /w established `pdo_sqlite` connection.

```
$sql = 'select 1 from "user"'; // user table does not exist
$res = $conn->prepare($sql)->executeQuery()->fetchAssociative(); // this does not throw, but the table does not exist!
var_dump($res); // prints "bool(false)", but this line should never be reached
$conn->executeQuery($sql); // this throws TableNotFoundException exception
```

I belive there must be some issue in DBAL, as `PDO::prepare()` throws an exception correctly - https://3v4l.org/DrSlj

#### Expected behaviour

`executeQuery` must throw an exception consistently no matter if called on connection or prepared statement. This behaviour is important, as no result - as currently returned when using prepared statement - is dangerous and can be interpreted wrongly.

**Comment by morozov** [comment]
I cannot reproduce this with the following script:
```php
<?php

use Doctrine\DBAL\DriverManager;

require 'vendor/autoload.php';

$conn = DriverManager::getConnection([
    'driver' => 'pdo_sqlite',
    'memory' => true,
]);
$sql = 'select 1 from "user"';
$conn->prepare($sql);
```

```
$ php 5526.php
PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1 no such table: user in /home/morozov/Projects/dbal/src/Driver/PDO/Connection.php:60
Stack trace:
#0 /home/morozov/Projects/dbal/src/Driver/PDO/Connection.php(60): PDO->prepare()
#1 /home/morozov/Projects/dbal/src/Connection.php(999): Doctrine\DBAL\Driver\PDO\Connection->prepare()
#2 /home/morozov/Projects/dbal/5526.php(12): Doctrine\DBAL\Connection->prepare()
#3 {main}

Next Doctrine\DBAL\Driver\PDO\Exception: SQLSTATE[HY000]: General error: 1 no such table: user in /home/morozov/Projects/dbal/src/Driver/PDO/Exception.php:30
Stack trace:
#0 /home/morozov/Projects/dbal/src/Driver/PDO/Connection.php(65): Doctrine\DBAL\Driver\PDO\Exception::new()
#1 /home/morozov/Projects/dbal/src/Connection.php(999): Doctrine\DBAL\Driver\PDO\Connection->prepare()
#2 /home/morozov/Projects/dbal/5526.php(12): Doctrine\DBAL\Connection->prepare()
#3 {main}

Next Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1 no such table: user in /home/morozov/Projects/dbal/src/Driver/API/SQLite/ExceptionConverter.php:55
Stack trace:
#0 /home/morozov/Projects/dbal/src/Connection.php(1814): Doctrine\DBAL\Driver\API\SQLite\ExceptionConverter->convert()
#1 /home/morozov/Projects/dbal/src/Connection.php(1749): Doctrine\DBAL\Connection->handleDriverException()
#2 /home/morozov/Projects/dbal/src/Connection.php(1001): Doctrine\DBAL\Connection->convertExceptionDuringQuery()
#3 /home/morozov/Projects/dbal/5526.php(12): Doctrine\DBAL\Connection->prepare()
#4 {main}
  thrown in /home/morozov/Projects/dbal/src/Driver/API/SQLite/ExceptionConverter.php on line 55
```
Do you use `PDO::ATTR_EMULATE_PREPARES`?

**Comment by mvorisek** [comment]
I am sorry for this issue, the problem was on my side.
